Add serviceaccount for AWS access through IRSA for EKS
valeriano-manassero/helm-charts pull request #106
Opened 2022-02-14 21:23 UTC by azisi

https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

2022-02-15 16:42 UTC, valeriano-manassero requested changes
Can you pls rebase and then bump up Chart version to 1.10.0 ? When done, pls use helm-docs to regenerate Trino README.md and we will be finally ready to start CI. ty!

2022-02-15 20:36 UTC, azisi commented
> Can you pls rebase and then bump up Chart version to 1.10.0 ? When done, pls use helm-docs to regenerate Trino README.md and we will be finally ready to start CI. ty!

done! have a look when you can and let me know 🙏🏽

2022-02-16 07:27 UTC, valeriano-manassero approved these changes

2022-02-16 07:35 UTC, merged

2022-02-16 07:35 UTC, valeriano-manassero commented
Merged! Ty!